In [33]:
import numpy as np
a = np.random.normal(0,1,25)
print("25 Random Number:",a)

25 Random Number: [-1.6591813   0.00476034 -1.60807007 -0.7718619   3.04871045  0.07671475
  1.018715   -0.31150846  1.54387953 -0.13048714 -1.21552069  0.28004147
 -1.44652894 -1.18685833 -0.24987362  1.16979953  0.7972783  -0.29953677
 -0.17141129  0.59703692  0.99504307 -1.20719366  1.80240165 -0.8270256
  0.12339904]


In [29]:
import numpy as np
x = np.random.random(30)
print("Original array:\n",x)
print("Mean:",np.mean(x))

Original array:
 [0.7637816  0.35643424 0.0271251  0.14854509 0.44843889 0.21072784
 0.6476749  0.99030247 0.31404272 0.37730924 0.8837318  0.2624883
 0.54917989 0.84635406 0.51610834 0.71309256 0.31604142 0.56645326
 0.55945446 0.79480563 0.27847681 0.83737105 0.42645596 0.97372099
 0.56549919 0.72679477 0.61444204 0.34390049 0.24198582 0.5910884 ]
Mean: 0.5297275782426801


In [38]:
import numpy as np

a = np.random.randint(1,101,(10,10))
print("10x10 Matrix:\n",a)

10x10 Matrix:
 [[53 77 62 96 25 91 78 48 36 62]
 [71  6 94 69 32 16 64 70 99 83]
 [83 26 10 84 75  1  9 13 12 79]
 [38 20 39 52 26 42  6 65 71 58]
 [70 34 25 23 18 13 16 73 35 48]
 [13 46 94 72 33 63 82 32 96 76]
 [48 84 89  7 58 79 99 11 12 33]
 [33 36  7 31 24 87 31 97 85 43]
 [75 52 29 42 68 36 20 92 81 22]
 [ 2  7 56 67 82 68 79 15  3 14]]
[96 99 84 71 73 96 99 97 92 82]


In [42]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:\n",x)
xmin, xmax = x.min(), x.max()
print("Minimum Values:{0} and \nMaximum Values:{1}".format(x.min(),x.max()))

Original Array:
 [[0.36170024 0.26891542 0.96249488 0.60051333 0.48201246]
 [0.04713402 0.56603147 0.90515886 0.39392824 0.06836745]
 [0.363441   0.15603734 0.32761196 0.4539566  0.65277879]
 [0.15226218 0.60262198 0.47174925 0.71014993 0.33869539]
 [0.3200839  0.23510344 0.74938456 0.91756805 0.09070786]]
Minimum Values:0.04713401986449284 and 
Maximum Values:0.9624948773597704


In [44]:
import numpy as np

f = np.array([1,2])
    
g = np.array([4,5])

d = np.dot(f,g)
print("Dot Product of Two Array:",d)

Dot Product of Two Array: 14


In [57]:
import numpy as np

x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
d = x + y
c = np.concatenate(d,axis=0)
print("Concatenate:",c)

Concatenate: [ 6  8  8 10]


In [60]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

print("Original array-a:{0} \nOriginal array-b:{1}".format(a,b))
c = np.intersect1d(a, b)
print("Common values:", c)


Original array-a:[1 2 3 2 3 4 3 4 5 6] 
Original array-b:[ 7  2 10  2  7  4  9  4  9  8]
Common values: [2 4]


In [65]:
import numpy as np
arr = np.array([10,5,8,4,7,2,3,1])
print("Sorting Array:",np.sort(arr))

Sorting Array: [ 1  2  3  4  5  7  8 10]
